---
- name: Download worker binaries - containerd
  get_url:
    url: '{{ item }}'
    dest: '{{ kubernetes_setup_location }}/'
  with_items: 
    - '{{ worker_binaries_sources.containerd }}'

- name: Extract containerd
  unarchive:
    src: '{{ kubernetes_setup_location }}/containerd-{{ worker_binaries_versions.containerd }}-linux-amd64.tar.gz'
    dest: '/opt/containerd'
    remote_src: yes

- name: Link containerd to bin
  file:
    src: /opt/containerd/bin/{{ item }}
    dest: /bin/{{ item }}
    state: link
  with_items:
    - containerd
    - containerd-shim
    - containerd-shim-runc-v1
    - containerd-shim-runc-v2
    - containerd-stress
    - ctr
