---
kubernetes_config_location: '/opt/kubernetes/config'

kubeconfig_location: '{{ kubernetes_config_location }}/kubeconfig'
kubeconfig_admin: '{{ kubeconfig_location }}/admin.kubeconfig'

netdata_config:
  service:
    type: 'NodePort'
  ingress:
    enabled: false
  database:
    persistence: false
  alarms:
    persistence: false
